crawler.thread.count=5
crawler.max.pages=10
crawler.seed.url=https://en.wikipedia.org/wiki/Java_(programming_language)
crawler.timeout.seconds=10
crawler.redis.hostname=localhost
crawler.redis.port=6379
crawler.redis.key=crawler:v1:visited
crawler.clean.start=true